#
# Module manifest for module 'MattBobkeCmdlets'
#
# Generated by: Matt Bobke
#
# Generated on: 4/14/2018
#

@{

    # Script module or binary module file associated with this manifest
    RootModule            = 'MattBobkeCmdlets.psm1'
    
    # Version number of this module.
    ModuleVersion         = '1.0'
    
    # ID used to uniquely identify this module
    GUID                  = 'a0bcdd49-cb72-44f5-b9f2-e42202a058b8'
    
    # Author of this module
    Author                = 'Matt Bobke'
    
    # Company or vendor of this module
    #CompanyName = 'Unknown'
    
    # Copyright statement for this module
    Copyright             = '(c) 2018 Matt Bobke. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description           = 'Some useful cmdlets that are not necessarily related in purpose or for any specific product.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion     = '5.1'
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of the .NET Framework required by this module
    # DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'None'
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module
    FunctionsToExport     = '*'
    
    # Cmdlets to export from this module
    CmdletsToExport       = '*'
    
    # Variables to export from this module
    VariablesToExport     = '*'
    
    # Aliases to export from this module
    AliasesToExport       = '*'
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    FileList              = @('MattBobkeCmdlets.ps1')
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess
    # PrivateData = ''
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
}